
import React from 'react';

const TermsOfMission: React.FC = () => {
  return (
    <div className="pt-32 pb-24 bg-white dark:bg-slate-950 min-h-screen transition-colors duration-300">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-left">
        <header className="mb-16 text-left">
          <h2 className="text-blue-600 font-black uppercase tracking-[0.2em] text-[10px] mb-4">Operational Guidelines</h2>
          <h1 className="text-4xl md:text-6xl font-black text-slate-900 dark:text-white mb-8 tracking-tighter">
            Terms of <span className="gradient-text">Mission</span>
          </h1>
          <div className="w-20 h-1.5 bg-blue-600 rounded-full"></div>
        </header>

        <div className="prose prose-blue max-w-none text-slate-700 dark:text-gray-400 font-medium leading-relaxed space-y-8">
          <section>
            <h3 className="text-2xl font-black text-slate-900 dark:text-white mb-4 tracking-tight">1. Scope of Participation</h3>
            <p>
              By entering the Mission Genesis terminal, participants agree to engage in immersive learning for the purpose of skill acquisition. Use of the platform for rote-learning automation or academic dishonesty is strictly prohibited and constitutes a breach of mission integrity.
            </p>
          </section>

          <section>
            <h3 className="text-2xl font-black text-slate-900 dark:text-white mb-4 tracking-tight">2. The Hunt Protocols</h3>
            <p>
              The annual 'Hunt' challenge operates under strict competition rules. Teams must be comprised of secondary students aged 12-18 currently enrolled in recognized educational institutions within the CEMAC region. All solutions submitted must be original and developed during the challenge timeframe.
            </p>
          </section>

          <section>
            <h3 className="text-2xl font-black text-slate-900 dark:text-white mb-4 tracking-tight">3. Verification Rights</h3>
            <p>
              Mission Genesis reserves the right to verify the competency scores through manual logic audits if a participant's progression curve shows statistical anomalies. This ensures that the 'Verification Engine' maintains its status as an elite credentialing standard.
            </p>
          </section>

          <section>
            <h3 className="text-2xl font-black text-slate-900 dark:text-white mb-4 tracking-tight">4. Intellectual Property</h3>
            <p>
              While the Mission Genesis platform is the property of Team S.C.A.A.M, all novel solutions generated by students during community challenges remain the property of the students, with a non-exclusive license granted to S.C.A.A.M for archival and showcase purposes.
            </p>
          </section>

          <div className="mt-16 pt-8 border-t border-slate-100 dark:border-white/5 text-sm text-slate-400 font-bold">
            Last Updated: January 2026 | Mission Code: GENESIS-BUEA-ALPHA
          </div>
        </div>
      </div>
    </div>
  );
};

export default TermsOfMission;
